apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: cofrap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard        # Minikube / Kind
  # storageClassName: standard-rwo    # GKE
  # storageClassName: gp2             # EKS
